version: "3.9"

services:
  backend:
    build: ./backend
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app        # 로컬 코드 마운트
      # - ./models:/app/_models  # (선택) 사전 다운로드 시
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    depends_on: [backend]
    restart: unless-stopped
    ports:
      - "3003:80"        # ▶︎ 호스트 3003 → 컨테이너 80
