# docker-compose.override.yml
services:
  backend:
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app:/app/app
      # - ${USERPROFILE}\\.paddlex:/root/.paddlex         # 선택
  frontend:
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:8000
    command: npm run dev
    volumes:
      - ./frontend:/app