services:
  frontend:
    command: sh -lc "test -x node_modules/.bin/next || (npm ci || npm install); npm run dev"
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:8000
      - CHOKIDAR_USEPOLLING=1     # Windows 파일 변경 감지 안정화
    ports:
      - "3003:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  frontend_node_modules: